version: '3.2'
services:
  db:
    image: mongo:3.4-jessie
    volumes:
      - type: volume
        source: mongo_db
        target: /data/db
        volume:
          nocopy: true
      - type: volume
        source: mongo_configdb
        target: /data/configdb
        volume:
          nocopy: true
#   ports:
#     - "127.0.0.1:27018:27017"
  app:
    image: sealroom-app:latest
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /opt/sealroom
    ports:
      - "127.0.0.1:8080:8080"
    user: ${UID:-1000}:${GID:-1000}
  webserver:
    image: sealroom-webserver:latest
    build:
      context: .
      dockerfile: webserver.dockerfile
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
volumes:
  mongo_db:
  mongo_configdb:
